version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/GUI_Web"
    schedule:
      interval: "daily"
    target-branch: main
    
  - package-ecosystem: "maven"
    directory: "/GUI_Web_Basic"
    schedule:
      interval: "daily"
    target-branch: main
    
  - package-ecosystem: "maven"
    directory: "/GUI_Web_Cucumber"
    schedule:
      interval: "daily"
    target-branch: main

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
