name: E2E Tests Custom

on:
  workflow_dispatch:
    inputs:
      targetBrowser:
        description: 'Choose Target Browser'
        default: 'chrome'
        type: choice
        options:
          - firefox
          - chrome
          - microsoftedge
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

jobs:
  Custom_Linux_Grid:
    runs-on: [ self-hosted, wfc ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log Tests Path
        run: echo ${{ github.event.inputs.testsPath }}

      - name: Set up Native Selenium Grid
        run: |
          if [ '${{ github.event.inputs.targetBrowser }}' == 'firefox' ]; then
            docker-compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=0 --scale firefox=4 -d --force-recreate
          elif [ '${{ github.event.inputs.targetBrowser }}' == 'chrome' ]; then
            docker-compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d --force-recreate
          elif [ '${{ github.event.inputs.targetBrowser }}' == 'microsoftedge' ]; then
            docker-compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=4 --scale firefox=0 -d --force-recreate
          else
            echo "Browser not supported"
          fi

      - name: Log Browser Version
        run: |
          if [ '${{ github.event.inputs.targetBrowser }}' == 'firefox' ]; then
            BROWSER_VERSION=$(docker run --rm selenium/node-firefox:4.16.1-20231212 firefox --version | awk "{print \$3}")
            echo "Firefox Browser Version: $BROWSER_VERSION"
          elif [ '${{ github.event.inputs.targetBrowser }}' == 'chrome' ]; then
            BROWSER_VERSION=$(docker run --rm selenium/node-chrome:120.0 google-chrome-stable --version | awk "{print \$3}")
             echo "Google Chrome Browser Version: $BROWSER_VERSION"
          elif [ '${{ github.event.inputs.targetBrowser }}' == 'microsoftedge' ]; then
            BROWSER_VERSION=$(docker run --rm selenium/node-edge:4.16.1-20231212 microsoft-edge --version | awk "{print \$3}")
            echo "Microsoft Edge Browser Version: $BROWSER_VERSION"
          else
            echo "Browser not supported"
          fi

      - name: Check running containers
        run: docker ps

      - name: Install Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
          check-latest: true

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt-get install -y maven
      - name: Check maven version
        run: mvn -version

      - name: Run tests
        continue-on-error: true
        run: |
          mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="LINUX" -DtargetBrowserName="${{ github.event.inputs.targetBrowser }}" -DheadlessExecution="true" -DgenerateAllureReportArchive="true" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -DcreateAnimatedGif="false" -Dtest="${{ github.event.inputs.testsPath }}"

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Custom_Linux_Grid_Allure
          path: "generatedReport_*.zip"

      - name: Upload Allure Report HTML as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Custom_Linux_Grid_Allure_HTML
          path: "allure-report/index.html"

      - name: Upload Extent Report as Pipeline Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Custom_Linux_Grid_Extent
          files: "extent-reports/ExtentReports_*.html"
