name: E2E Tests

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  GUI_Web:
    name: Run GUI Web Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Set up Native Selenium Grid
        run: docker-compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d

      - name: Set up Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Check running containers
        run: docker ps

      - name: Run tests on Linux
        continue-on-error: true
        run: |
          mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="LINUX" -DmaximumPerformanceMode="2" -DtargetBrowserName="GoogleChrome" -DcreateAnimatedGif="true" -DgenerateAllureReportArchive="true"

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Linux Desktop Browsers Tests Allure Report
          path: "generatedReport_*.zip"

      - name: Upload Allure Report HTML as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: Linux Desktop Browsers Tests Allure Report HTML
           path: "allure-report/index.html"

      - name: Upload Extent Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Linux Desktop Browsers Tests Extent Report
          path: "extent-reports/ExtentReports_*.html"
